#=========================================================================
# TravisCI Setup
#=========================================================================

language: c

#-------------------------------------------------------------------------
# addons
#-------------------------------------------------------------------------

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-6
#       - make
#       - autoconf
#       - libfl-dev
#       - bison

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:

 - wget http://www.veripool.org/ftp/verilator-4.008.tgz
 - tar -xzvf verilator-4.008.tgz
 - cd verilator-4.008
 - ./configure
 - make

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - echo "done"

